// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckinRecordUpdate is the builder for updating DailyCheckinRecord entities.
type DailyCheckinRecordUpdate struct {
	config
	hooks    []Hook
	mutation *DailyCheckinRecordMutation
}

// Where appends a list predicates to the DailyCheckinRecordUpdate builder.
func (_u *DailyCheckinRecordUpdate) Where(ps ...predicate.DailyCheckinRecord) *DailyCheckinRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyCheckinRecordUpdate) SetUpdatedAt(v time.Time) *DailyCheckinRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckinRecordUpdate) SetUserID(v int64) *DailyCheckinRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableUserID(v *int64) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *DailyCheckinRecordUpdate) SetCheckinDate(v time.Time) *DailyCheckinRecordUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableCheckinDate(v *time.Time) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *DailyCheckinRecordUpdate) SetTimezone(v string) *DailyCheckinRecordUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableTimezone(v *string) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetBaseReward sets the "base_reward" field.
func (_u *DailyCheckinRecordUpdate) SetBaseReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.ResetBaseReward()
	_u.mutation.SetBaseReward(v)
	return _u
}

// SetNillableBaseReward sets the "base_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableBaseReward(v *float64) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetBaseReward(*v)
	}
	return _u
}

// AddBaseReward adds value to the "base_reward" field.
func (_u *DailyCheckinRecordUpdate) AddBaseReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.AddBaseReward(v)
	return _u
}

// SetBonusReward sets the "bonus_reward" field.
func (_u *DailyCheckinRecordUpdate) SetBonusReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.ResetBonusReward()
	_u.mutation.SetBonusReward(v)
	return _u
}

// SetNillableBonusReward sets the "bonus_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableBonusReward(v *float64) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetBonusReward(*v)
	}
	return _u
}

// AddBonusReward adds value to the "bonus_reward" field.
func (_u *DailyCheckinRecordUpdate) AddBonusReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.AddBonusReward(v)
	return _u
}

// SetTotalReward sets the "total_reward" field.
func (_u *DailyCheckinRecordUpdate) SetTotalReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.ResetTotalReward()
	_u.mutation.SetTotalReward(v)
	return _u
}

// SetNillableTotalReward sets the "total_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableTotalReward(v *float64) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetTotalReward(*v)
	}
	return _u
}

// AddTotalReward adds value to the "total_reward" field.
func (_u *DailyCheckinRecordUpdate) AddTotalReward(v float64) *DailyCheckinRecordUpdate {
	_u.mutation.AddTotalReward(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *DailyCheckinRecordUpdate) SetStreakDays(v int) *DailyCheckinRecordUpdate {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdate) SetNillableStreakDays(v *int) *DailyCheckinRecordUpdate {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *DailyCheckinRecordUpdate) AddStreakDays(v int) *DailyCheckinRecordUpdate {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckinRecordUpdate) SetUser(v *User) *DailyCheckinRecordUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DailyCheckinRecordMutation object of the builder.
func (_u *DailyCheckinRecordUpdate) Mutation() *DailyCheckinRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckinRecordUpdate) ClearUser() *DailyCheckinRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyCheckinRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckinRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyCheckinRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckinRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyCheckinRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailycheckinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckinRecordUpdate) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := dailycheckinrecord.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "DailyCheckinRecord.timezone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckinRecord.user"`)
	}
	return nil
}

func (_u *DailyCheckinRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckinrecord.Table, dailycheckinrecord.Columns, sqlgraph.NewFieldSpec(dailycheckinrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailycheckinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(dailycheckinrecord.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(dailycheckinrecord.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBaseReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldBaseReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBonusReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldBonusReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldTotalReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldTotalReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(dailycheckinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(dailycheckinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinrecord.UserTable,
			Columns: []string{dailycheckinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinrecord.UserTable,
			Columns: []string{dailycheckinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyCheckinRecordUpdateOne is the builder for updating a single DailyCheckinRecord entity.
type DailyCheckinRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyCheckinRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DailyCheckinRecordUpdateOne) SetUpdatedAt(v time.Time) *DailyCheckinRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyCheckinRecordUpdateOne) SetUserID(v int64) *DailyCheckinRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableUserID(v *int64) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *DailyCheckinRecordUpdateOne) SetCheckinDate(v time.Time) *DailyCheckinRecordUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableCheckinDate(v *time.Time) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *DailyCheckinRecordUpdateOne) SetTimezone(v string) *DailyCheckinRecordUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableTimezone(v *string) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetBaseReward sets the "base_reward" field.
func (_u *DailyCheckinRecordUpdateOne) SetBaseReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.ResetBaseReward()
	_u.mutation.SetBaseReward(v)
	return _u
}

// SetNillableBaseReward sets the "base_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableBaseReward(v *float64) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetBaseReward(*v)
	}
	return _u
}

// AddBaseReward adds value to the "base_reward" field.
func (_u *DailyCheckinRecordUpdateOne) AddBaseReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.AddBaseReward(v)
	return _u
}

// SetBonusReward sets the "bonus_reward" field.
func (_u *DailyCheckinRecordUpdateOne) SetBonusReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.ResetBonusReward()
	_u.mutation.SetBonusReward(v)
	return _u
}

// SetNillableBonusReward sets the "bonus_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableBonusReward(v *float64) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetBonusReward(*v)
	}
	return _u
}

// AddBonusReward adds value to the "bonus_reward" field.
func (_u *DailyCheckinRecordUpdateOne) AddBonusReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.AddBonusReward(v)
	return _u
}

// SetTotalReward sets the "total_reward" field.
func (_u *DailyCheckinRecordUpdateOne) SetTotalReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.ResetTotalReward()
	_u.mutation.SetTotalReward(v)
	return _u
}

// SetNillableTotalReward sets the "total_reward" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableTotalReward(v *float64) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetTotalReward(*v)
	}
	return _u
}

// AddTotalReward adds value to the "total_reward" field.
func (_u *DailyCheckinRecordUpdateOne) AddTotalReward(v float64) *DailyCheckinRecordUpdateOne {
	_u.mutation.AddTotalReward(v)
	return _u
}

// SetStreakDays sets the "streak_days" field.
func (_u *DailyCheckinRecordUpdateOne) SetStreakDays(v int) *DailyCheckinRecordUpdateOne {
	_u.mutation.ResetStreakDays()
	_u.mutation.SetStreakDays(v)
	return _u
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_u *DailyCheckinRecordUpdateOne) SetNillableStreakDays(v *int) *DailyCheckinRecordUpdateOne {
	if v != nil {
		_u.SetStreakDays(*v)
	}
	return _u
}

// AddStreakDays adds value to the "streak_days" field.
func (_u *DailyCheckinRecordUpdateOne) AddStreakDays(v int) *DailyCheckinRecordUpdateOne {
	_u.mutation.AddStreakDays(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DailyCheckinRecordUpdateOne) SetUser(v *User) *DailyCheckinRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DailyCheckinRecordMutation object of the builder.
func (_u *DailyCheckinRecordUpdateOne) Mutation() *DailyCheckinRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DailyCheckinRecordUpdateOne) ClearUser() *DailyCheckinRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the DailyCheckinRecordUpdate builder.
func (_u *DailyCheckinRecordUpdateOne) Where(ps ...predicate.DailyCheckinRecord) *DailyCheckinRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyCheckinRecordUpdateOne) Select(field string, fields ...string) *DailyCheckinRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyCheckinRecord entity.
func (_u *DailyCheckinRecordUpdateOne) Save(ctx context.Context) (*DailyCheckinRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyCheckinRecordUpdateOne) SaveX(ctx context.Context) *DailyCheckinRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyCheckinRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyCheckinRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DailyCheckinRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dailycheckinrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyCheckinRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Timezone(); ok {
		if err := dailycheckinrecord.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "DailyCheckinRecord.timezone": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyCheckinRecord.user"`)
	}
	return nil
}

func (_u *DailyCheckinRecordUpdateOne) sqlSave(ctx context.Context) (_node *DailyCheckinRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailycheckinrecord.Table, dailycheckinrecord.Columns, sqlgraph.NewFieldSpec(dailycheckinrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyCheckinRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailycheckinrecord.FieldID)
		for _, f := range fields {
			if !dailycheckinrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailycheckinrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dailycheckinrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(dailycheckinrecord.FieldCheckinDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(dailycheckinrecord.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBaseReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldBaseReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBonusReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldBonusReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldTotalReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalReward(); ok {
		_spec.AddField(dailycheckinrecord.FieldTotalReward, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StreakDays(); ok {
		_spec.SetField(dailycheckinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreakDays(); ok {
		_spec.AddField(dailycheckinrecord.FieldStreakDays, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinrecord.UserTable,
			Columns: []string{dailycheckinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinrecord.UserTable,
			Columns: []string{dailycheckinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DailyCheckinRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailycheckinrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
