// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckinRecordCreate is the builder for creating a DailyCheckinRecord entity.
type DailyCheckinRecordCreate struct {
	config
	mutation *DailyCheckinRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DailyCheckinRecordCreate) SetCreatedAt(v time.Time) *DailyCheckinRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableCreatedAt(v *time.Time) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DailyCheckinRecordCreate) SetUpdatedAt(v time.Time) *DailyCheckinRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableUpdatedAt(v *time.Time) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DailyCheckinRecordCreate) SetUserID(v int64) *DailyCheckinRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCheckinDate sets the "checkin_date" field.
func (_c *DailyCheckinRecordCreate) SetCheckinDate(v time.Time) *DailyCheckinRecordCreate {
	_c.mutation.SetCheckinDate(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *DailyCheckinRecordCreate) SetTimezone(v string) *DailyCheckinRecordCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableTimezone(v *string) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetBaseReward sets the "base_reward" field.
func (_c *DailyCheckinRecordCreate) SetBaseReward(v float64) *DailyCheckinRecordCreate {
	_c.mutation.SetBaseReward(v)
	return _c
}

// SetNillableBaseReward sets the "base_reward" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableBaseReward(v *float64) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetBaseReward(*v)
	}
	return _c
}

// SetBonusReward sets the "bonus_reward" field.
func (_c *DailyCheckinRecordCreate) SetBonusReward(v float64) *DailyCheckinRecordCreate {
	_c.mutation.SetBonusReward(v)
	return _c
}

// SetNillableBonusReward sets the "bonus_reward" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableBonusReward(v *float64) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetBonusReward(*v)
	}
	return _c
}

// SetTotalReward sets the "total_reward" field.
func (_c *DailyCheckinRecordCreate) SetTotalReward(v float64) *DailyCheckinRecordCreate {
	_c.mutation.SetTotalReward(v)
	return _c
}

// SetNillableTotalReward sets the "total_reward" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableTotalReward(v *float64) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetTotalReward(*v)
	}
	return _c
}

// SetStreakDays sets the "streak_days" field.
func (_c *DailyCheckinRecordCreate) SetStreakDays(v int) *DailyCheckinRecordCreate {
	_c.mutation.SetStreakDays(v)
	return _c
}

// SetNillableStreakDays sets the "streak_days" field if the given value is not nil.
func (_c *DailyCheckinRecordCreate) SetNillableStreakDays(v *int) *DailyCheckinRecordCreate {
	if v != nil {
		_c.SetStreakDays(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DailyCheckinRecordCreate) SetUser(v *User) *DailyCheckinRecordCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DailyCheckinRecordMutation object of the builder.
func (_c *DailyCheckinRecordCreate) Mutation() *DailyCheckinRecordMutation {
	return _c.mutation
}

// Save creates the DailyCheckinRecord in the database.
func (_c *DailyCheckinRecordCreate) Save(ctx context.Context) (*DailyCheckinRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyCheckinRecordCreate) SaveX(ctx context.Context) *DailyCheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyCheckinRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyCheckinRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyCheckinRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dailycheckinrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dailycheckinrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := dailycheckinrecord.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.BaseReward(); !ok {
		v := dailycheckinrecord.DefaultBaseReward
		_c.mutation.SetBaseReward(v)
	}
	if _, ok := _c.mutation.BonusReward(); !ok {
		v := dailycheckinrecord.DefaultBonusReward
		_c.mutation.SetBonusReward(v)
	}
	if _, ok := _c.mutation.TotalReward(); !ok {
		v := dailycheckinrecord.DefaultTotalReward
		_c.mutation.SetTotalReward(v)
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		v := dailycheckinrecord.DefaultStreakDays
		_c.mutation.SetStreakDays(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyCheckinRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyCheckinRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DailyCheckinRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DailyCheckinRecord.user_id"`)}
	}
	if _, ok := _c.mutation.CheckinDate(); !ok {
		return &ValidationError{Name: "checkin_date", err: errors.New(`ent: missing required field "DailyCheckinRecord.checkin_date"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "DailyCheckinRecord.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := dailycheckinrecord.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "DailyCheckinRecord.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseReward(); !ok {
		return &ValidationError{Name: "base_reward", err: errors.New(`ent: missing required field "DailyCheckinRecord.base_reward"`)}
	}
	if _, ok := _c.mutation.BonusReward(); !ok {
		return &ValidationError{Name: "bonus_reward", err: errors.New(`ent: missing required field "DailyCheckinRecord.bonus_reward"`)}
	}
	if _, ok := _c.mutation.TotalReward(); !ok {
		return &ValidationError{Name: "total_reward", err: errors.New(`ent: missing required field "DailyCheckinRecord.total_reward"`)}
	}
	if _, ok := _c.mutation.StreakDays(); !ok {
		return &ValidationError{Name: "streak_days", err: errors.New(`ent: missing required field "DailyCheckinRecord.streak_days"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DailyCheckinRecord.user"`)}
	}
	return nil
}

func (_c *DailyCheckinRecordCreate) sqlSave(ctx context.Context) (*DailyCheckinRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyCheckinRecordCreate) createSpec() (*DailyCheckinRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyCheckinRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailycheckinrecord.Table, sqlgraph.NewFieldSpec(dailycheckinrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dailycheckinrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dailycheckinrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CheckinDate(); ok {
		_spec.SetField(dailycheckinrecord.FieldCheckinDate, field.TypeTime, value)
		_node.CheckinDate = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(dailycheckinrecord.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.BaseReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBaseReward, field.TypeFloat64, value)
		_node.BaseReward = value
	}
	if value, ok := _c.mutation.BonusReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldBonusReward, field.TypeFloat64, value)
		_node.BonusReward = value
	}
	if value, ok := _c.mutation.TotalReward(); ok {
		_spec.SetField(dailycheckinrecord.FieldTotalReward, field.TypeFloat64, value)
		_node.TotalReward = value
	}
	if value, ok := _c.mutation.StreakDays(); ok {
		_spec.SetField(dailycheckinrecord.FieldStreakDays, field.TypeInt, value)
		_node.StreakDays = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailycheckinrecord.UserTable,
			Columns: []string{dailycheckinrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyCheckinRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyCheckinRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyCheckinRecordCreate) OnConflict(opts ...sql.ConflictOption) *DailyCheckinRecordUpsertOne {
	_c.conflict = opts
	return &DailyCheckinRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyCheckinRecordCreate) OnConflictColumns(columns ...string) *DailyCheckinRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyCheckinRecordUpsertOne{
		create: _c,
	}
}

type (
	// DailyCheckinRecordUpsertOne is the builder for "upsert"-ing
	//  one DailyCheckinRecord node.
	DailyCheckinRecordUpsertOne struct {
		create *DailyCheckinRecordCreate
	}

	// DailyCheckinRecordUpsert is the "OnConflict" setter.
	DailyCheckinRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyCheckinRecordUpsert) SetUpdatedAt(v time.Time) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateUpdatedAt() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DailyCheckinRecordUpsert) SetUserID(v int64) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateUserID() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldUserID)
	return u
}

// SetCheckinDate sets the "checkin_date" field.
func (u *DailyCheckinRecordUpsert) SetCheckinDate(v time.Time) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldCheckinDate, v)
	return u
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateCheckinDate() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldCheckinDate)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *DailyCheckinRecordUpsert) SetTimezone(v string) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateTimezone() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldTimezone)
	return u
}

// SetBaseReward sets the "base_reward" field.
func (u *DailyCheckinRecordUpsert) SetBaseReward(v float64) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldBaseReward, v)
	return u
}

// UpdateBaseReward sets the "base_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateBaseReward() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldBaseReward)
	return u
}

// AddBaseReward adds v to the "base_reward" field.
func (u *DailyCheckinRecordUpsert) AddBaseReward(v float64) *DailyCheckinRecordUpsert {
	u.Add(dailycheckinrecord.FieldBaseReward, v)
	return u
}

// SetBonusReward sets the "bonus_reward" field.
func (u *DailyCheckinRecordUpsert) SetBonusReward(v float64) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldBonusReward, v)
	return u
}

// UpdateBonusReward sets the "bonus_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateBonusReward() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldBonusReward)
	return u
}

// AddBonusReward adds v to the "bonus_reward" field.
func (u *DailyCheckinRecordUpsert) AddBonusReward(v float64) *DailyCheckinRecordUpsert {
	u.Add(dailycheckinrecord.FieldBonusReward, v)
	return u
}

// SetTotalReward sets the "total_reward" field.
func (u *DailyCheckinRecordUpsert) SetTotalReward(v float64) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldTotalReward, v)
	return u
}

// UpdateTotalReward sets the "total_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateTotalReward() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldTotalReward)
	return u
}

// AddTotalReward adds v to the "total_reward" field.
func (u *DailyCheckinRecordUpsert) AddTotalReward(v float64) *DailyCheckinRecordUpsert {
	u.Add(dailycheckinrecord.FieldTotalReward, v)
	return u
}

// SetStreakDays sets the "streak_days" field.
func (u *DailyCheckinRecordUpsert) SetStreakDays(v int) *DailyCheckinRecordUpsert {
	u.Set(dailycheckinrecord.FieldStreakDays, v)
	return u
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsert) UpdateStreakDays() *DailyCheckinRecordUpsert {
	u.SetExcluded(dailycheckinrecord.FieldStreakDays)
	return u
}

// AddStreakDays adds v to the "streak_days" field.
func (u *DailyCheckinRecordUpsert) AddStreakDays(v int) *DailyCheckinRecordUpsert {
	u.Add(dailycheckinrecord.FieldStreakDays, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyCheckinRecordUpsertOne) UpdateNewValues() *DailyCheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dailycheckinrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DailyCheckinRecordUpsertOne) Ignore() *DailyCheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyCheckinRecordUpsertOne) DoNothing() *DailyCheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyCheckinRecordCreate.OnConflict
// documentation for more info.
func (u *DailyCheckinRecordUpsertOne) Update(set func(*DailyCheckinRecordUpsert)) *DailyCheckinRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyCheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyCheckinRecordUpsertOne) SetUpdatedAt(v time.Time) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateUpdatedAt() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DailyCheckinRecordUpsertOne) SetUserID(v int64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateUserID() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *DailyCheckinRecordUpsertOne) SetCheckinDate(v time.Time) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateCheckinDate() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetTimezone sets the "timezone" field.
func (u *DailyCheckinRecordUpsertOne) SetTimezone(v string) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateTimezone() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateTimezone()
	})
}

// SetBaseReward sets the "base_reward" field.
func (u *DailyCheckinRecordUpsertOne) SetBaseReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetBaseReward(v)
	})
}

// AddBaseReward adds v to the "base_reward" field.
func (u *DailyCheckinRecordUpsertOne) AddBaseReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddBaseReward(v)
	})
}

// UpdateBaseReward sets the "base_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateBaseReward() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateBaseReward()
	})
}

// SetBonusReward sets the "bonus_reward" field.
func (u *DailyCheckinRecordUpsertOne) SetBonusReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetBonusReward(v)
	})
}

// AddBonusReward adds v to the "bonus_reward" field.
func (u *DailyCheckinRecordUpsertOne) AddBonusReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddBonusReward(v)
	})
}

// UpdateBonusReward sets the "bonus_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateBonusReward() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateBonusReward()
	})
}

// SetTotalReward sets the "total_reward" field.
func (u *DailyCheckinRecordUpsertOne) SetTotalReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetTotalReward(v)
	})
}

// AddTotalReward adds v to the "total_reward" field.
func (u *DailyCheckinRecordUpsertOne) AddTotalReward(v float64) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddTotalReward(v)
	})
}

// UpdateTotalReward sets the "total_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateTotalReward() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateTotalReward()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *DailyCheckinRecordUpsertOne) SetStreakDays(v int) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *DailyCheckinRecordUpsertOne) AddStreakDays(v int) *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertOne) UpdateStreakDays() *DailyCheckinRecordUpsertOne {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *DailyCheckinRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyCheckinRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyCheckinRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DailyCheckinRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DailyCheckinRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DailyCheckinRecordCreateBulk is the builder for creating many DailyCheckinRecord entities in bulk.
type DailyCheckinRecordCreateBulk struct {
	config
	err      error
	builders []*DailyCheckinRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the DailyCheckinRecord entities in the database.
func (_c *DailyCheckinRecordCreateBulk) Save(ctx context.Context) ([]*DailyCheckinRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyCheckinRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyCheckinRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyCheckinRecordCreateBulk) SaveX(ctx context.Context) []*DailyCheckinRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyCheckinRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyCheckinRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyCheckinRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyCheckinRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyCheckinRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *DailyCheckinRecordUpsertBulk {
	_c.conflict = opts
	return &DailyCheckinRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyCheckinRecordCreateBulk) OnConflictColumns(columns ...string) *DailyCheckinRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyCheckinRecordUpsertBulk{
		create: _c,
	}
}

// DailyCheckinRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of DailyCheckinRecord nodes.
type DailyCheckinRecordUpsertBulk struct {
	create *DailyCheckinRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyCheckinRecordUpsertBulk) UpdateNewValues() *DailyCheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dailycheckinrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyCheckinRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DailyCheckinRecordUpsertBulk) Ignore() *DailyCheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyCheckinRecordUpsertBulk) DoNothing() *DailyCheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyCheckinRecordCreateBulk.OnConflict
// documentation for more info.
func (u *DailyCheckinRecordUpsertBulk) Update(set func(*DailyCheckinRecordUpsert)) *DailyCheckinRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyCheckinRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DailyCheckinRecordUpsertBulk) SetUpdatedAt(v time.Time) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateUpdatedAt() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DailyCheckinRecordUpsertBulk) SetUserID(v int64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateUserID() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *DailyCheckinRecordUpsertBulk) SetCheckinDate(v time.Time) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateCheckinDate() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateCheckinDate()
	})
}

// SetTimezone sets the "timezone" field.
func (u *DailyCheckinRecordUpsertBulk) SetTimezone(v string) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateTimezone() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateTimezone()
	})
}

// SetBaseReward sets the "base_reward" field.
func (u *DailyCheckinRecordUpsertBulk) SetBaseReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetBaseReward(v)
	})
}

// AddBaseReward adds v to the "base_reward" field.
func (u *DailyCheckinRecordUpsertBulk) AddBaseReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddBaseReward(v)
	})
}

// UpdateBaseReward sets the "base_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateBaseReward() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateBaseReward()
	})
}

// SetBonusReward sets the "bonus_reward" field.
func (u *DailyCheckinRecordUpsertBulk) SetBonusReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetBonusReward(v)
	})
}

// AddBonusReward adds v to the "bonus_reward" field.
func (u *DailyCheckinRecordUpsertBulk) AddBonusReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddBonusReward(v)
	})
}

// UpdateBonusReward sets the "bonus_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateBonusReward() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateBonusReward()
	})
}

// SetTotalReward sets the "total_reward" field.
func (u *DailyCheckinRecordUpsertBulk) SetTotalReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetTotalReward(v)
	})
}

// AddTotalReward adds v to the "total_reward" field.
func (u *DailyCheckinRecordUpsertBulk) AddTotalReward(v float64) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddTotalReward(v)
	})
}

// UpdateTotalReward sets the "total_reward" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateTotalReward() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateTotalReward()
	})
}

// SetStreakDays sets the "streak_days" field.
func (u *DailyCheckinRecordUpsertBulk) SetStreakDays(v int) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.SetStreakDays(v)
	})
}

// AddStreakDays adds v to the "streak_days" field.
func (u *DailyCheckinRecordUpsertBulk) AddStreakDays(v int) *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.AddStreakDays(v)
	})
}

// UpdateStreakDays sets the "streak_days" field to the value that was provided on create.
func (u *DailyCheckinRecordUpsertBulk) UpdateStreakDays() *DailyCheckinRecordUpsertBulk {
	return u.Update(func(s *DailyCheckinRecordUpsert) {
		s.UpdateStreakDays()
	})
}

// Exec executes the query.
func (u *DailyCheckinRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DailyCheckinRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyCheckinRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyCheckinRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
