// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/dailycheckinrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DailyCheckinRecord is the model entity for the DailyCheckinRecord schema.
type DailyCheckinRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Check-in date in the user's selected timezone
	CheckinDate time.Time `json:"checkin_date,omitempty"`
	// Timezone used to derive checkin_date
	Timezone string `json:"timezone,omitempty"`
	// Base reward credited for this check-in
	BaseReward float64 `json:"base_reward,omitempty"`
	// Extra streak reward credited for this check-in
	BonusReward float64 `json:"bonus_reward,omitempty"`
	// Total reward credited for this check-in
	TotalReward float64 `json:"total_reward,omitempty"`
	// Consecutive check-in days after this check-in
	StreakDays int `json:"streak_days,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DailyCheckinRecordQuery when eager-loading is set.
	Edges        DailyCheckinRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DailyCheckinRecordEdges holds the relations/edges for other nodes in the graph.
type DailyCheckinRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyCheckinRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyCheckinRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailycheckinrecord.FieldBaseReward, dailycheckinrecord.FieldBonusReward, dailycheckinrecord.FieldTotalReward:
			values[i] = new(sql.NullFloat64)
		case dailycheckinrecord.FieldID, dailycheckinrecord.FieldUserID, dailycheckinrecord.FieldStreakDays:
			values[i] = new(sql.NullInt64)
		case dailycheckinrecord.FieldTimezone:
			values[i] = new(sql.NullString)
		case dailycheckinrecord.FieldCreatedAt, dailycheckinrecord.FieldUpdatedAt, dailycheckinrecord.FieldCheckinDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyCheckinRecord fields.
func (_m *DailyCheckinRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailycheckinrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case dailycheckinrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dailycheckinrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dailycheckinrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case dailycheckinrecord.FieldCheckinDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_date", values[i])
			} else if value.Valid {
				_m.CheckinDate = value.Time
			}
		case dailycheckinrecord.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case dailycheckinrecord.FieldBaseReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_reward", values[i])
			} else if value.Valid {
				_m.BaseReward = value.Float64
			}
		case dailycheckinrecord.FieldBonusReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_reward", values[i])
			} else if value.Valid {
				_m.BonusReward = value.Float64
			}
		case dailycheckinrecord.FieldTotalReward:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_reward", values[i])
			} else if value.Valid {
				_m.TotalReward = value.Float64
			}
		case dailycheckinrecord.FieldStreakDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field streak_days", values[i])
			} else if value.Valid {
				_m.StreakDays = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyCheckinRecord.
// This includes values selected through modifiers, order, etc.
func (_m *DailyCheckinRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the DailyCheckinRecord entity.
func (_m *DailyCheckinRecord) QueryUser() *UserQuery {
	return NewDailyCheckinRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this DailyCheckinRecord.
// Note that you need to call DailyCheckinRecord.Unwrap() before calling this method if this DailyCheckinRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyCheckinRecord) Update() *DailyCheckinRecordUpdateOne {
	return NewDailyCheckinRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyCheckinRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyCheckinRecord) Unwrap() *DailyCheckinRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyCheckinRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyCheckinRecord) String() string {
	var builder strings.Builder
	builder.WriteString("DailyCheckinRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("checkin_date=")
	builder.WriteString(_m.CheckinDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("base_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseReward))
	builder.WriteString(", ")
	builder.WriteString("bonus_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusReward))
	builder.WriteString(", ")
	builder.WriteString("total_reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalReward))
	builder.WriteString(", ")
	builder.WriteString("streak_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreakDays))
	builder.WriteByte(')')
	return builder.String()
}

// DailyCheckinRecords is a parsable slice of DailyCheckinRecord.
type DailyCheckinRecords []*DailyCheckinRecord
