// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/welfarerecord"
)

// WelfareRecordCreate is the builder for creating a WelfareRecord entity.
type WelfareRecordCreate struct {
	config
	mutation *WelfareRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *WelfareRecordCreate) SetCreatedAt(v time.Time) *WelfareRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WelfareRecordCreate) SetNillableCreatedAt(v *time.Time) *WelfareRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WelfareRecordCreate) SetUpdatedAt(v time.Time) *WelfareRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WelfareRecordCreate) SetNillableUpdatedAt(v *time.Time) *WelfareRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WelfareRecordCreate) SetUserID(v int64) *WelfareRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *WelfareRecordCreate) SetUserEmail(v string) *WelfareRecordCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *WelfareRecordCreate) SetAmount(v float64) *WelfareRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRemarks sets the "remarks" field.
func (_c *WelfareRecordCreate) SetRemarks(v string) *WelfareRecordCreate {
	_c.mutation.SetRemarks(v)
	return _c
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_c *WelfareRecordCreate) SetNillableRemarks(v *string) *WelfareRecordCreate {
	if v != nil {
		_c.SetRemarks(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WelfareRecordCreate) SetStatus(v string) *WelfareRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WelfareRecordCreate) SetNillableStatus(v *string) *WelfareRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WelfareRecordCreate) SetUser(v *User) *WelfareRecordCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the WelfareRecordMutation object of the builder.
func (_c *WelfareRecordCreate) Mutation() *WelfareRecordMutation {
	return _c.mutation
}

// Save creates the WelfareRecord in the database.
func (_c *WelfareRecordCreate) Save(ctx context.Context) (*WelfareRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WelfareRecordCreate) SaveX(ctx context.Context) *WelfareRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WelfareRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WelfareRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WelfareRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := welfarerecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := welfarerecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Remarks(); !ok {
		v := welfarerecord.DefaultRemarks
		_c.mutation.SetRemarks(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := welfarerecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WelfareRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WelfareRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WelfareRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WelfareRecord.user_id"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "WelfareRecord.user_email"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := welfarerecord.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.user_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "WelfareRecord.amount"`)}
	}
	if _, ok := _c.mutation.Remarks(); !ok {
		return &ValidationError{Name: "remarks", err: errors.New(`ent: missing required field "WelfareRecord.remarks"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WelfareRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := welfarerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WelfareRecord.user"`)}
	}
	return nil
}

func (_c *WelfareRecordCreate) sqlSave(ctx context.Context) (*WelfareRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WelfareRecordCreate) createSpec() (*WelfareRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &WelfareRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(welfarerecord.Table, sqlgraph.NewFieldSpec(welfarerecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(welfarerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(welfarerecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(welfarerecord.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(welfarerecord.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Remarks(); ok {
		_spec.SetField(welfarerecord.FieldRemarks, field.TypeString, value)
		_node.Remarks = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(welfarerecord.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarerecord.UserTable,
			Columns: []string{welfarerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WelfareRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WelfareRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WelfareRecordCreate) OnConflict(opts ...sql.ConflictOption) *WelfareRecordUpsertOne {
	_c.conflict = opts
	return &WelfareRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WelfareRecordCreate) OnConflictColumns(columns ...string) *WelfareRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WelfareRecordUpsertOne{
		create: _c,
	}
}

type (
	// WelfareRecordUpsertOne is the builder for "upsert"-ing
	//  one WelfareRecord node.
	WelfareRecordUpsertOne struct {
		create *WelfareRecordCreate
	}

	// WelfareRecordUpsert is the "OnConflict" setter.
	WelfareRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareRecordUpsert) SetUpdatedAt(v time.Time) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateUpdatedAt() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *WelfareRecordUpsert) SetUserID(v int64) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateUserID() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *WelfareRecordUpsert) SetUserEmail(v string) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateUserEmail() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldUserEmail)
	return u
}

// SetAmount sets the "amount" field.
func (u *WelfareRecordUpsert) SetAmount(v float64) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateAmount() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *WelfareRecordUpsert) AddAmount(v float64) *WelfareRecordUpsert {
	u.Add(welfarerecord.FieldAmount, v)
	return u
}

// SetRemarks sets the "remarks" field.
func (u *WelfareRecordUpsert) SetRemarks(v string) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldRemarks, v)
	return u
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateRemarks() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldRemarks)
	return u
}

// SetStatus sets the "status" field.
func (u *WelfareRecordUpsert) SetStatus(v string) *WelfareRecordUpsert {
	u.Set(welfarerecord.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareRecordUpsert) UpdateStatus() *WelfareRecordUpsert {
	u.SetExcluded(welfarerecord.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WelfareRecordUpsertOne) UpdateNewValues() *WelfareRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(welfarerecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WelfareRecordUpsertOne) Ignore() *WelfareRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WelfareRecordUpsertOne) DoNothing() *WelfareRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WelfareRecordCreate.OnConflict
// documentation for more info.
func (u *WelfareRecordUpsertOne) Update(set func(*WelfareRecordUpsert)) *WelfareRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WelfareRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareRecordUpsertOne) SetUpdatedAt(v time.Time) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateUpdatedAt() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WelfareRecordUpsertOne) SetUserID(v int64) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateUserID() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *WelfareRecordUpsertOne) SetUserEmail(v string) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateUserEmail() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUserEmail()
	})
}

// SetAmount sets the "amount" field.
func (u *WelfareRecordUpsertOne) SetAmount(v float64) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *WelfareRecordUpsertOne) AddAmount(v float64) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateAmount() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetRemarks sets the "remarks" field.
func (u *WelfareRecordUpsertOne) SetRemarks(v string) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateRemarks() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateRemarks()
	})
}

// SetStatus sets the "status" field.
func (u *WelfareRecordUpsertOne) SetStatus(v string) *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareRecordUpsertOne) UpdateStatus() *WelfareRecordUpsertOne {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *WelfareRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WelfareRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WelfareRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WelfareRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WelfareRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WelfareRecordCreateBulk is the builder for creating many WelfareRecord entities in bulk.
type WelfareRecordCreateBulk struct {
	config
	err      error
	builders []*WelfareRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the WelfareRecord entities in the database.
func (_c *WelfareRecordCreateBulk) Save(ctx context.Context) ([]*WelfareRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WelfareRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WelfareRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WelfareRecordCreateBulk) SaveX(ctx context.Context) []*WelfareRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WelfareRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WelfareRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WelfareRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WelfareRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *WelfareRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *WelfareRecordUpsertBulk {
	_c.conflict = opts
	return &WelfareRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WelfareRecordCreateBulk) OnConflictColumns(columns ...string) *WelfareRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WelfareRecordUpsertBulk{
		create: _c,
	}
}

// WelfareRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of WelfareRecord nodes.
type WelfareRecordUpsertBulk struct {
	create *WelfareRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WelfareRecordUpsertBulk) UpdateNewValues() *WelfareRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(welfarerecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WelfareRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WelfareRecordUpsertBulk) Ignore() *WelfareRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WelfareRecordUpsertBulk) DoNothing() *WelfareRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WelfareRecordCreateBulk.OnConflict
// documentation for more info.
func (u *WelfareRecordUpsertBulk) Update(set func(*WelfareRecordUpsert)) *WelfareRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WelfareRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WelfareRecordUpsertBulk) SetUpdatedAt(v time.Time) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateUpdatedAt() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *WelfareRecordUpsertBulk) SetUserID(v int64) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateUserID() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *WelfareRecordUpsertBulk) SetUserEmail(v string) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateUserEmail() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateUserEmail()
	})
}

// SetAmount sets the "amount" field.
func (u *WelfareRecordUpsertBulk) SetAmount(v float64) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *WelfareRecordUpsertBulk) AddAmount(v float64) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateAmount() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetRemarks sets the "remarks" field.
func (u *WelfareRecordUpsertBulk) SetRemarks(v string) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateRemarks() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateRemarks()
	})
}

// SetStatus sets the "status" field.
func (u *WelfareRecordUpsertBulk) SetStatus(v string) *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WelfareRecordUpsertBulk) UpdateStatus() *WelfareRecordUpsertBulk {
	return u.Update(func(s *WelfareRecordUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *WelfareRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WelfareRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WelfareRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WelfareRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
