// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/welfarerecord"
)

// WelfareRecord is the model entity for the WelfareRecord schema.
type WelfareRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// User ID
	UserID int64 `json:"user_id,omitempty"`
	// User Email
	UserEmail string `json:"user_email,omitempty"`
	// Welfare Bonus Amount
	Amount float64 `json:"amount,omitempty"`
	// Remarks (template: Date + Leaderboard spending + #Rank)
	Remarks string `json:"remarks,omitempty"`
	// Status (success / revoked)
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WelfareRecordQuery when eager-loading is set.
	Edges        WelfareRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WelfareRecordEdges holds the relations/edges for other nodes in the graph.
type WelfareRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WelfareRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WelfareRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case welfarerecord.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case welfarerecord.FieldID, welfarerecord.FieldUserID:
			values[i] = new(sql.NullInt64)
		case welfarerecord.FieldUserEmail, welfarerecord.FieldRemarks, welfarerecord.FieldStatus:
			values[i] = new(sql.NullString)
		case welfarerecord.FieldCreatedAt, welfarerecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WelfareRecord fields.
func (_m *WelfareRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case welfarerecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case welfarerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case welfarerecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case welfarerecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case welfarerecord.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case welfarerecord.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case welfarerecord.FieldRemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remarks", values[i])
			} else if value.Valid {
				_m.Remarks = value.String
			}
		case welfarerecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WelfareRecord.
// This includes values selected through modifiers, order, etc.
func (_m *WelfareRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the WelfareRecord entity.
func (_m *WelfareRecord) QueryUser() *UserQuery {
	return NewWelfareRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this WelfareRecord.
// Note that you need to call WelfareRecord.Unwrap() before calling this method if this WelfareRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WelfareRecord) Update() *WelfareRecordUpdateOne {
	return NewWelfareRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WelfareRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WelfareRecord) Unwrap() *WelfareRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WelfareRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WelfareRecord) String() string {
	var builder strings.Builder
	builder.WriteString("WelfareRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("remarks=")
	builder.WriteString(_m.Remarks)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// WelfareRecords is a parsable slice of WelfareRecord.
type WelfareRecords []*WelfareRecord
