// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/welfarerecord"
)

// WelfareRecordUpdate is the builder for updating WelfareRecord entities.
type WelfareRecordUpdate struct {
	config
	hooks    []Hook
	mutation *WelfareRecordMutation
}

// Where appends a list predicates to the WelfareRecordUpdate builder.
func (_u *WelfareRecordUpdate) Where(ps ...predicate.WelfareRecord) *WelfareRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WelfareRecordUpdate) SetUpdatedAt(v time.Time) *WelfareRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WelfareRecordUpdate) SetUserID(v int64) *WelfareRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WelfareRecordUpdate) SetNillableUserID(v *int64) *WelfareRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *WelfareRecordUpdate) SetUserEmail(v string) *WelfareRecordUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *WelfareRecordUpdate) SetNillableUserEmail(v *string) *WelfareRecordUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WelfareRecordUpdate) SetAmount(v float64) *WelfareRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WelfareRecordUpdate) SetNillableAmount(v *float64) *WelfareRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WelfareRecordUpdate) AddAmount(v float64) *WelfareRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *WelfareRecordUpdate) SetRemarks(v string) *WelfareRecordUpdate {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *WelfareRecordUpdate) SetNillableRemarks(v *string) *WelfareRecordUpdate {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WelfareRecordUpdate) SetStatus(v string) *WelfareRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WelfareRecordUpdate) SetNillableStatus(v *string) *WelfareRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WelfareRecordUpdate) SetUser(v *User) *WelfareRecordUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WelfareRecordMutation object of the builder.
func (_u *WelfareRecordUpdate) Mutation() *WelfareRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WelfareRecordUpdate) ClearUser() *WelfareRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WelfareRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WelfareRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WelfareRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WelfareRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WelfareRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := welfarerecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WelfareRecordUpdate) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := welfarerecord.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := welfarerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WelfareRecord.user"`)
	}
	return nil
}

func (_u *WelfareRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(welfarerecord.Table, welfarerecord.Columns, sqlgraph.NewFieldSpec(welfarerecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(welfarerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(welfarerecord.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(welfarerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(welfarerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(welfarerecord.FieldRemarks, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(welfarerecord.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarerecord.UserTable,
			Columns: []string{welfarerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarerecord.UserTable,
			Columns: []string{welfarerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{welfarerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WelfareRecordUpdateOne is the builder for updating a single WelfareRecord entity.
type WelfareRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WelfareRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WelfareRecordUpdateOne) SetUpdatedAt(v time.Time) *WelfareRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WelfareRecordUpdateOne) SetUserID(v int64) *WelfareRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WelfareRecordUpdateOne) SetNillableUserID(v *int64) *WelfareRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *WelfareRecordUpdateOne) SetUserEmail(v string) *WelfareRecordUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *WelfareRecordUpdateOne) SetNillableUserEmail(v *string) *WelfareRecordUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *WelfareRecordUpdateOne) SetAmount(v float64) *WelfareRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *WelfareRecordUpdateOne) SetNillableAmount(v *float64) *WelfareRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *WelfareRecordUpdateOne) AddAmount(v float64) *WelfareRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemarks sets the "remarks" field.
func (_u *WelfareRecordUpdateOne) SetRemarks(v string) *WelfareRecordUpdateOne {
	_u.mutation.SetRemarks(v)
	return _u
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_u *WelfareRecordUpdateOne) SetNillableRemarks(v *string) *WelfareRecordUpdateOne {
	if v != nil {
		_u.SetRemarks(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WelfareRecordUpdateOne) SetStatus(v string) *WelfareRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WelfareRecordUpdateOne) SetNillableStatus(v *string) *WelfareRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WelfareRecordUpdateOne) SetUser(v *User) *WelfareRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WelfareRecordMutation object of the builder.
func (_u *WelfareRecordUpdateOne) Mutation() *WelfareRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WelfareRecordUpdateOne) ClearUser() *WelfareRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the WelfareRecordUpdate builder.
func (_u *WelfareRecordUpdateOne) Where(ps ...predicate.WelfareRecord) *WelfareRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WelfareRecordUpdateOne) Select(field string, fields ...string) *WelfareRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WelfareRecord entity.
func (_u *WelfareRecordUpdateOne) Save(ctx context.Context) (*WelfareRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WelfareRecordUpdateOne) SaveX(ctx context.Context) *WelfareRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WelfareRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WelfareRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WelfareRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := welfarerecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WelfareRecordUpdateOne) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := welfarerecord.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := welfarerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WelfareRecord.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WelfareRecord.user"`)
	}
	return nil
}

func (_u *WelfareRecordUpdateOne) sqlSave(ctx context.Context) (_node *WelfareRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(welfarerecord.Table, welfarerecord.Columns, sqlgraph.NewFieldSpec(welfarerecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WelfareRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, welfarerecord.FieldID)
		for _, f := range fields {
			if !welfarerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != welfarerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(welfarerecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(welfarerecord.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(welfarerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(welfarerecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remarks(); ok {
		_spec.SetField(welfarerecord.FieldRemarks, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(welfarerecord.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarerecord.UserTable,
			Columns: []string{welfarerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   welfarerecord.UserTable,
			Columns: []string{welfarerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WelfareRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{welfarerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
