package repository

import (
	"context"
	"testing"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/alicebob/miniredis/v2"
	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/require"
)

func TestCodexTicketLegacyHarvesterBarrierOnlyPausesNewClaims(t *testing.T) {
	server := miniredis.RunT(t)
	client := redis.NewClient(&redis.Options{Addr: server.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	cache, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	ctx := context.Background()
	require.NoError(t, client.Set(ctx, "{codex-ticket}:legacy-harvester", "deployment-owner", time.Hour).Err())
	state, err := cache.ClaimCodexTicketHarvest(ctx, 30, "source", "owner", 2, time.Minute)
	require.NoError(t, err)
	require.False(t, state.Acquired)
	require.False(t, state.Running)
	require.True(t, state.RetryAfter.IsZero(), "deployment wait is not an upstream rejection cooldown")
	require.Empty(t, state.LastError)
	require.EqualValues(t, 0, client.Exists(ctx, "{codex-ticket}:lease:30", "{codex-ticket}:active", "{codex-ticket}:cooldown:30").Val(), "barrier must not consume capacity or fabricate failure state")
	require.NoError(t, client.Del(ctx, "{codex-ticket}:legacy-harvester").Err())
	state, err = cache.ClaimCodexTicketHarvest(ctx, 30, "source", "owner", 2, time.Minute)
	require.NoError(t, err)
	require.True(t, state.Acquired)
	// Adding the barrier later does not revoke already-owned new-version jobs.
	require.NoError(t, client.Set(ctx, "{codex-ticket}:legacy-harvester", "deployment-owner", time.Hour).Err())
	refreshed, err := cache.RefreshCodexTicketHarvest(ctx, 30, "owner", time.Minute)
	require.NoError(t, err)
	require.True(t, refreshed)
	refreshed, err = cache.FinishCodexTicketHarvest(ctx, 30, "source", "owner", 0, "")
	require.NoError(t, err)
	require.True(t, refreshed)
}

func TestCodexTicketSharedLeaseCapacityExpiryAndStaleOwner(t *testing.T) {
	server := miniredis.RunT(t)
	now := time.Now().Truncate(time.Second)
	server.SetTime(now)
	client := redis.NewClient(&redis.Options{Addr: server.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	first, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	second, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	ctx := context.Background()
	claim, err := first.ClaimCodexTicketHarvest(ctx, 10, "source", "owner-a", 1, 90*time.Second)
	require.NoError(t, err)
	require.True(t, claim.Acquired)
	claim, err = second.ClaimCodexTicketHarvest(ctx, 10, "source", "owner-b", 1, 90*time.Second)
	require.NoError(t, err)
	require.False(t, claim.Acquired)
	require.True(t, claim.Running)
	claim, err = second.ClaimCodexTicketHarvest(ctx, 11, "other", "owner-c", 1, 90*time.Second)
	require.NoError(t, err)
	require.False(t, claim.Acquired)
	require.False(t, claim.Running, "capacity is shared across accounts and instances")
	refreshed, err := second.RefreshCodexTicketHarvest(ctx, 10, "owner-b", 90*time.Second)
	require.NoError(t, err)
	require.False(t, refreshed)
	refreshed, err = first.RefreshCodexTicketHarvest(ctx, 10, "owner-a", 90*time.Second)
	require.NoError(t, err)
	require.True(t, refreshed)
	server.FastForward(91 * time.Second)
	server.SetTime(now.Add(91 * time.Second))
	claim, err = second.ClaimCodexTicketHarvest(ctx, 10, "source", "owner-b", 1, 90*time.Second)
	require.NoError(t, err)
	require.True(t, claim.Acquired)
	ok, err = first.FinishCodexTicketHarvest(ctx, 10, "source", "owner-a", 5*time.Minute, "old failure")
	require.NoError(t, err)
	require.False(t, ok)
	state, err := second.GetCodexTicketHarvestState(ctx, 10, "source")
	require.NoError(t, err)
	require.True(t, state.Running)
	require.True(t, state.RetryAfter.IsZero(), "expired owner must not poison replacement cooldown")
	ok, err = second.FinishCodexTicketHarvest(ctx, 10, "source", "owner-b", 0, "")
	require.NoError(t, err)
	require.True(t, ok)
	claim, err = second.ClaimCodexTicketHarvest(ctx, 11, "other", "owner-c", 1, 90*time.Second)
	require.NoError(t, err)
	require.True(t, claim.Acquired)
}

func TestCodexTicketSharedCooldownSurvivesNewCacheAndRespectsSource(t *testing.T) {
	server := miniredis.RunT(t)
	now := time.Now().Truncate(time.Second)
	server.SetTime(now)
	client := redis.NewClient(&redis.Options{Addr: server.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	cache, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	ctx := context.Background()
	_, err := cache.ClaimCodexTicketHarvest(ctx, 20, "revision-1", "owner-a", 2, time.Minute)
	require.NoError(t, err)
	finished, err := cache.FinishCodexTicketHarvest(ctx, 20, "revision-1", "owner-a", 5*time.Minute, "Authentication rejected (HTTP 401)")
	require.NoError(t, err)
	require.True(t, finished)
	restarted, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	state, err := restarted.GetCodexTicketHarvestState(ctx, 20, "revision-1")
	require.NoError(t, err)
	require.WithinDuration(t, now.Add(5*time.Minute), state.RetryAfter, time.Second)
	require.Contains(t, state.LastError, "401")
	claim, err := restarted.ClaimCodexTicketHarvest(ctx, 20, "revision-1", "owner-b", 2, time.Minute)
	require.NoError(t, err)
	require.False(t, claim.Acquired)
	require.Equal(t, state.RetryAfter, claim.RetryAfter)
	claim, err = restarted.ClaimCodexTicketHarvest(ctx, 20, "revision-2", "owner-b", 2, time.Minute)
	require.NoError(t, err)
	require.True(t, claim.Acquired, "explicit new route/configuration has a different source")
	_, err = restarted.FinishCodexTicketHarvest(ctx, 20, "revision-2", "owner-b", 5*time.Minute, "HTTP 401")
	require.NoError(t, err)
	server.FastForward(301 * time.Second)
	server.SetTime(now.Add(301 * time.Second))
	claim, err = cache.ClaimCodexTicketHarvest(ctx, 20, "revision-2", "owner-c", 2, time.Minute)
	require.NoError(t, err)
	require.True(t, claim.Acquired)
}

func TestCodexTicket429SwitchIgnoresStoredCooldownOnlyWhenOff(t *testing.T) {
	server := miniredis.RunT(t)
	server.SetTime(time.Now())
	client := redis.NewClient(&redis.Options{Addr: server.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	cache, ok := NewGatewayCache(client).(service.CodexTicketHarvestCoordinator)
	require.True(t, ok)
	on := service.With429Enforcement(context.Background(), true)
	off := service.With429Enforcement(context.Background(), false)
	_, err := cache.ClaimCodexTicketHarvest(on, 44, "revision", "old", 2, time.Minute)
	require.NoError(t, err)
	_, err = cache.FinishCodexTicketHarvest(on, 44, "revision", "old", 5*time.Minute, "HTTP 429")
	require.NoError(t, err)
	blocked, err := cache.ClaimCodexTicketHarvest(on, 44, "revision", "new", 2, time.Minute)
	require.NoError(t, err)
	require.False(t, blocked.Acquired)
	require.False(t, blocked.RetryAfter.IsZero())
	observation, err := cache.GetCodexTicketHarvestState(off, 44, "revision")
	require.NoError(t, err)
	require.True(t, observation.RetryAfter.IsZero())
	require.Contains(t, observation.LastError, "429")
	allowed, err := cache.ClaimCodexTicketHarvest(off, 44, "revision", "new", 2, time.Minute)
	require.NoError(t, err)
	require.True(t, allowed.Acquired)
	_, err = cache.FinishCodexTicketHarvest(off, 44, "revision", "new", 5*time.Minute, "HTTP 429")
	require.NoError(t, err)
	state, err := cache.GetCodexTicketHarvestState(on, 44, "revision")
	require.NoError(t, err)
	require.True(t, state.RetryAfter.IsZero(), "OFF records no new cooldown")
}
