// Code generated by ent, DO NOT EDIT.

package dailycheckinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dailycheckinrecord type in the database.
	Label = "daily_checkin_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCheckinDate holds the string denoting the checkin_date field in the database.
	FieldCheckinDate = "checkin_date"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldBaseReward holds the string denoting the base_reward field in the database.
	FieldBaseReward = "base_reward"
	// FieldBonusReward holds the string denoting the bonus_reward field in the database.
	FieldBonusReward = "bonus_reward"
	// FieldTotalReward holds the string denoting the total_reward field in the database.
	FieldTotalReward = "total_reward"
	// FieldStreakDays holds the string denoting the streak_days field in the database.
	FieldStreakDays = "streak_days"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the dailycheckinrecord in the database.
	Table = "daily_checkin_records"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "daily_checkin_records"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for dailycheckinrecord fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCheckinDate,
	FieldTimezone,
	FieldBaseReward,
	FieldBonusReward,
	FieldTotalReward,
	FieldStreakDays,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultBaseReward holds the default value on creation for the "base_reward" field.
	DefaultBaseReward float64
	// DefaultBonusReward holds the default value on creation for the "bonus_reward" field.
	DefaultBonusReward float64
	// DefaultTotalReward holds the default value on creation for the "total_reward" field.
	DefaultTotalReward float64
	// DefaultStreakDays holds the default value on creation for the "streak_days" field.
	DefaultStreakDays int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the DailyCheckinRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCheckinDate orders the results by the checkin_date field.
func ByCheckinDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinDate, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByBaseReward orders the results by the base_reward field.
func ByBaseReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseReward, opts...).ToFunc()
}

// ByBonusReward orders the results by the bonus_reward field.
func ByBonusReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusReward, opts...).ToFunc()
}

// ByTotalReward orders the results by the total_reward field.
func ByTotalReward(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReward, opts...).ToFunc()
}

// ByStreakDays orders the results by the streak_days field.
func ByStreakDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreakDays, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
