// Code generated by ent, DO NOT EDIT.

package dailycheckinrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldTimezone, v))
}

// BaseReward applies equality check predicate on the "base_reward" field. It's identical to BaseRewardEQ.
func BaseReward(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldBaseReward, v))
}

// BonusReward applies equality check predicate on the "bonus_reward" field. It's identical to BonusRewardEQ.
func BonusReward(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldBonusReward, v))
}

// TotalReward applies equality check predicate on the "total_reward" field. It's identical to TotalRewardEQ.
func TotalReward(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldTotalReward, v))
}

// StreakDays applies equality check predicate on the "streak_days" field. It's identical to StreakDaysEQ.
func StreakDays(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldStreakDays, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v time.Time) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldCheckinDate, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldContainsFold(FieldTimezone, v))
}

// BaseRewardEQ applies the EQ predicate on the "base_reward" field.
func BaseRewardEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldBaseReward, v))
}

// BaseRewardNEQ applies the NEQ predicate on the "base_reward" field.
func BaseRewardNEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldBaseReward, v))
}

// BaseRewardIn applies the In predicate on the "base_reward" field.
func BaseRewardIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldBaseReward, vs...))
}

// BaseRewardNotIn applies the NotIn predicate on the "base_reward" field.
func BaseRewardNotIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldBaseReward, vs...))
}

// BaseRewardGT applies the GT predicate on the "base_reward" field.
func BaseRewardGT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldBaseReward, v))
}

// BaseRewardGTE applies the GTE predicate on the "base_reward" field.
func BaseRewardGTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldBaseReward, v))
}

// BaseRewardLT applies the LT predicate on the "base_reward" field.
func BaseRewardLT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldBaseReward, v))
}

// BaseRewardLTE applies the LTE predicate on the "base_reward" field.
func BaseRewardLTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldBaseReward, v))
}

// BonusRewardEQ applies the EQ predicate on the "bonus_reward" field.
func BonusRewardEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldBonusReward, v))
}

// BonusRewardNEQ applies the NEQ predicate on the "bonus_reward" field.
func BonusRewardNEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldBonusReward, v))
}

// BonusRewardIn applies the In predicate on the "bonus_reward" field.
func BonusRewardIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldBonusReward, vs...))
}

// BonusRewardNotIn applies the NotIn predicate on the "bonus_reward" field.
func BonusRewardNotIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldBonusReward, vs...))
}

// BonusRewardGT applies the GT predicate on the "bonus_reward" field.
func BonusRewardGT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldBonusReward, v))
}

// BonusRewardGTE applies the GTE predicate on the "bonus_reward" field.
func BonusRewardGTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldBonusReward, v))
}

// BonusRewardLT applies the LT predicate on the "bonus_reward" field.
func BonusRewardLT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldBonusReward, v))
}

// BonusRewardLTE applies the LTE predicate on the "bonus_reward" field.
func BonusRewardLTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldBonusReward, v))
}

// TotalRewardEQ applies the EQ predicate on the "total_reward" field.
func TotalRewardEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldTotalReward, v))
}

// TotalRewardNEQ applies the NEQ predicate on the "total_reward" field.
func TotalRewardNEQ(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldTotalReward, v))
}

// TotalRewardIn applies the In predicate on the "total_reward" field.
func TotalRewardIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldTotalReward, vs...))
}

// TotalRewardNotIn applies the NotIn predicate on the "total_reward" field.
func TotalRewardNotIn(vs ...float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldTotalReward, vs...))
}

// TotalRewardGT applies the GT predicate on the "total_reward" field.
func TotalRewardGT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldTotalReward, v))
}

// TotalRewardGTE applies the GTE predicate on the "total_reward" field.
func TotalRewardGTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldTotalReward, v))
}

// TotalRewardLT applies the LT predicate on the "total_reward" field.
func TotalRewardLT(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldTotalReward, v))
}

// TotalRewardLTE applies the LTE predicate on the "total_reward" field.
func TotalRewardLTE(v float64) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldTotalReward, v))
}

// StreakDaysEQ applies the EQ predicate on the "streak_days" field.
func StreakDaysEQ(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldStreakDays, v))
}

// StreakDaysNEQ applies the NEQ predicate on the "streak_days" field.
func StreakDaysNEQ(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldStreakDays, v))
}

// StreakDaysIn applies the In predicate on the "streak_days" field.
func StreakDaysIn(vs ...int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldStreakDays, vs...))
}

// StreakDaysNotIn applies the NotIn predicate on the "streak_days" field.
func StreakDaysNotIn(vs ...int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldStreakDays, vs...))
}

// StreakDaysGT applies the GT predicate on the "streak_days" field.
func StreakDaysGT(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldStreakDays, v))
}

// StreakDaysGTE applies the GTE predicate on the "streak_days" field.
func StreakDaysGTE(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldStreakDays, v))
}

// StreakDaysLT applies the LT predicate on the "streak_days" field.
func StreakDaysLT(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldStreakDays, v))
}

// StreakDaysLTE applies the LTE predicate on the "streak_days" field.
func StreakDaysLTE(v int) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldStreakDays, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.FieldContainsFold(FieldStatus, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyCheckinRecord) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyCheckinRecord) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyCheckinRecord) predicate.DailyCheckinRecord {
	return predicate.DailyCheckinRecord(sql.NotPredicates(p))
}
